#!/usr/bin/env sh

FILTER="${1}"
SCRIPTNAME="azure_cleanup"

if [[ -z "${AZURE_SUBSCRIPTION_ID}" ]]; then
	echo "${SCRIPTNAME}: AZURE_SUBSCRIPTION_ID must be set!"
	exit -1
fi

rgs=($(azure group list --json | jq -r ".[].name | select(contains(\"${FILTER}\"))" -))
if ! (( ${#rgs[@]} > 0 )); then
	echo "${SCRIPTNAME}: No matching groups. Exiting!"
	exit 0
fi

echo "${SCRIPTNAME}: DELETE: (sub: ${AZURE_SUBSCRIPTION_ID}): ${rgs[@]}"
echo "${SCRIPTNAME}: CONFIRM? ('yes' proceeds, everything else exits)"
read -r CONFIRM
if [[ "${CONFIRM}" != "yes" ]]; then
	echo "${SCRIPTNAME}: Only 'yes' will allow deletion! Exiting!"
	exit -1
fi

for group in ${rgs}; do
	echo "${SCRIPTNAME}: Deleting resource group: ${group}"
	azure group delete --quiet --subscription "${AZURE_SUBSCRIPTION_ID}" "${group}"
	echo "${SCRIPTNAME}: Delete succuessful (${group})"
done

